version: '3'

services:
  rabbitmq:
    hostname: "rabbitmq"
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - "./data:/var/lib/rabbitmq/mnesia/"
    ports:
      - "5672:5672"
      - "15672:15672"
  elasticsearch:
    hostname: "elasticsearch"
    image: elasticsearch:8.9.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - "./data01:/usr/share/elasticsearch/data"
    networks:
      - es-net
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    depends_on: 
      - elasticsearch
    hostname: "kibana"
    image: kibana:8.9.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    ports:
      - "5601:5601"
networks:
  es-net:
    driver: bridge